### ISSUE TITLE
Broken CRON job due to suspended installation

### ISSUE THREAD

**Issue by korthout** [repohistory/repohistory#7]
**Describe the bug**
The CRON job workflow is broken.

>RequestError [HttpError]: This installation has been suspended

**To Reproduce**
See the [latest runs in GitHub](https://github.com/repohistory/repohistory/actions/workflows/cron.yaml).

**Expected behavior**
The CRON job should be able to handle "suspended installations"

**Additional context**

<details><summary>Full logs</summary>
<p>

```
Run node dist/cron.js
/home/runner/work/repohistory/repohistory/node_modules/@octokit/request/dist-node/index.js:112
      const error = new import_request_error.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: This installation has been suspended
    at /home/runner/work/repohistory/repohistory/node_modules/@octokit/request/dist-node/index.js:112:21
    at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/repohistory/repohistory/actions/runs/11009801930/job/30570262134#step:6:10)5:5)
    at async getInstallationAuthentication (/home/runner/work/repohistory/repohistory/node_modules/@octokit/auth-app/dist-node/index.js:238:7)
    at async hook (/home/runner/work/repohistory/repohistory/node_modules/@octokit/auth-app/dist-node/index.js:393:32)
    at async requestWithGraphqlErrorHandling (/home/runner/work/repohistory/repohistory/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
    at async Job.doExecute (/home/runner/work/repohistory/repohistory/node_modules/bottleneck/light.js:405:18) {
  status: 403,
  response: {
    url: 'https://api.github.com/app/installations/55159774/access_tokens',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 24 Sep 2024 08:19:[11](https://github.com/repohistory/repohistory/actions/runs/11009801930/job/30570262134#step:6:12) GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'github.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '9C43:2E8630:3[14](https://github.com/repohistory/repohistory/actions/runs/11009801930/job/30570262134#step:6:15)AAED:5E29C8A:66F275FF',
      'x-xss-protection': '0'
    },
    data: {
      message: 'This installation has been suspended',
      documentation_url: 'https://docs.github.com/rest/reference/apps#create-an-installation-access-token-for-an-app',
      status: '403'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/app/installations/55[15](https://github.com/repohistory/repohistory/actions/runs/11009801930/job/30570262134#step:6:16)9774/access_tokens',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/3.1.2 octokit.js/3.1.2 octokit-core.js/5.0.1 Node.js/18.20.4 (linux; x64)',
      authorization: 'bearer [REDACTED]'
    },
    request: { hook: [Function: bound bound register], retryCount: 0 }
  }
}

Node.js v18.20.4
Error: Process completed with exit code 1.
```

</p>
</details>

**Comment by m4xshen** [comment]
@korthout the issue is fixed now!

**Comment by korthout** [comment]
Thanks 🙏
